### PR TITLE
Initiate CLA - Aziz ABOUCHI

### PR DESCRIPTION
**Pull request by aabouchi**
Please edit the title of the Pull Request to: "Initiate EasyCLA - <your name>"

This is a trivial test PR to initiate an EasyCLA check/signing process.
It is not intended to get merged.

### CODE REVIEW

**Comment by wrathwolf** [comment]
Hi Aziz,
I see in our system that you've become the CLA Manager for SFR.  Can you try the test again?

**Review by wrathwolf — COMMENTED** [review]
Hello @aabouchi 
It appears that you still have not added any approval criteria for SFR yet.
Please let me know if you need any further assistance, or please open a ticket at https://support.linuxfoundation.org

**Comment by aabouchi** [comment]
I've restarted from the beginning and that works now, thank you for your help Casey !

**Comment by wrathwolf** [comment]
This issue was resolved in PR #52

**Pull request closed without merging**
